import pytest
from dataclasses import dataclass, field, MISSING
from typing import Optional

from hmoe2.serializable import Serializable

# ==========================================
# TEST FIXTURES & DUMMY CLASSES
# ==========================================

@dataclass
class SimpleConfig(Serializable):
    """A basic serializable dataclass with default values."""
    name: str
    threshold: float = 0.5
    is_active: bool = True

@dataclass
class NestedConfig(Serializable):
    """A complex serializable dataclass containing another serializable object."""
    name: str
    child: Optional[SimpleConfig] = None
    max_retries: int = 3

@dataclass
class DefaultNameConfig(Serializable):
    """A dataclass where even the 'name' field has a default."""
    name: str = "unnamed"
    value: int = 10

@dataclass
class FactoryConfig(Serializable):
    """A dataclass using default_factory to test MISSING default comparisons."""
    name: str
    items: list = field(default_factory=list)


# ==========================================
# SERIALIZATION TESTS
# ==========================================

def test_serialize_string_reduction():
    """
    Validates Step 4: If only 'name' is customized (all other fields match 
    their defaults), the method should return just the name as a string.
    """
    # Threshold and is_active are left as their defaults (0.5 and True)
    config = SimpleConfig(name="baseline_model")
    
    result = config.serialize()
    
    # Should reduce to a simple string
    assert isinstance(result, str)
    assert result == "baseline_model"

def test_serialize_dictionary_output_and_default_dropping():
    """
    Validates Steps 2 and 5: Non-default fields should be included in a 
    dictionary, and default fields should be completely dropped.
    """
    # We change 'threshold', but leave 'is_active' as default True
    config = SimpleConfig(name="aggressive_model", threshold=0.9)
    
    result = config.serialize()
    
    assert isinstance(result, dict)
    assert result["name"] == "aggressive_model"
    assert result["threshold"] == 0.9
    
    # is_active was default, so it should be missing from the dictionary
    assert "is_active" not in result

def test_serialize_nested_objects():
    """
    Validates Step 3: Nested objects that implement serialize() should 
    have their own serialization logic triggered recursively.
    """
    child_config = SimpleConfig(name="child_node", threshold=0.1)
    parent_config = NestedConfig(name="parent_node", child=child_config)
    
    result = parent_config.serialize()
    
    assert isinstance(result, dict)
    assert result["name"] == "parent_node"
    
    # The child object should be recursively serialized into a dict
    assert isinstance(result["child"], dict)
    assert result["child"]["name"] == "child_node"
    assert result["child"]["threshold"] == 0.1

def test_serialize_name_always_included():
    """
    Validates Step 2 exception: The 'name' field is explicitly protected 
    from being dropped, even if it equals its default value.
    """
    # Instantiate with the exact default values
    config = DefaultNameConfig(name="unnamed", value=10)
    
    result = config.serialize()
    
    # Since 'value' is dropped, only 'name' remains.
    # Therefore, it reduces to a string containing the default name.
    assert result == "unnamed"

def test_serialize_default_factory_handling():
    """
    Validates handling of dataclass fields using default_factory.
    Because f.default is dataclasses.MISSING in these cases, val == f.default 
    evaluates to False, meaning factory-initialized fields are ALWAYS serialized.
    """
    config = FactoryConfig(name="list_holder")
    
    # Items is an empty list generated by the factory
    result = config.serialize()
    
    assert isinstance(result, dict)
    assert result["name"] == "list_holder"
    # The list is serialized because it does not equal MISSING
    assert "items" in result
    assert result["items"] == []

def test_serialize_nested_string_reduction():
    """
    Validates that if a nested object reduces to a string, the parent 
    dictionary correctly maps the key to that string.
    """
    # Child only has 'name' customized, so it reduces to a string
    child_config = SimpleConfig(name="simple_child")
    parent_config = NestedConfig(name="parent", child=child_config)
    
    result = parent_config.serialize()
    
    assert isinstance(result, dict)
    assert result["name"] == "parent"
    # Child serialization reduced to string
    assert result["child"] == "simple_child"